### ISSUE TITLE
Task 4-5 (JS, Classes)

### ISSUE THREAD

**Issue by ala-n** [NadezhdaSukhotskaya/practice2019#1]
[-] _filterByAuthor, _filterByTags, _filterByDate have a side-effect 
```
.slice(skip, skip + top).sort(function (x, y) {
            return x.createdAt.getDate() - y.createdAt.getDate();
        });
```
- thats it.
As the result getPage in general will not work properly if more then one filter applied.
[-] _findingIndex : consider Array.prototype.findIndex inside.
[-] remove method doesn't use  _findingIndex utilty
[=] (cosmetic) edit method possibly could be optimized by Object.assing method

[+1] very nice style, code structured

Thanks!
Current score 8 (for lab 4) and  8+1 (for lab 5)

**Comment by NadezhdaSukhotskaya** [comment]
@ala-n  Thaks. Bug fixed.
commit: 318cc7508bcb044f1b4559d41ffb01493aa3cd61

**Comment by alexey-kozlenkov** [comment]
9 for lab 4 then
